version: '3.8'

services:
  react-app:
    image: springshop-frontend-web 
    container_name: springshop-frontend

    build:
      context: .
      dockerfile: dockerfile
    
    ports:
      - "5173:80" 
    
    restart: always